services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/data
      - ./matrix:/app/matrix  # For development hot-reload
      - ./staticfiles:/app/staticfiles  # For static files
    environment:
      - DJANGO_SETTINGS_MODULE=eisenhower_matrix.settings
      - PYTHONPATH=/app
      - GUNICORN_WORKERS=3
      - GUNICORN_TIMEOUT=120
      - GUNICORN_MAX_REQUESTS=1000
      - NODE_ENV=production
    command: /app/entrypoint.sh
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local