# Generated by Django 5.1.3 on 2024-11-27 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_task_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matrices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='matrix.matrix'),
        ),
        migrations.CreateModel(
            name='MatrixAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='matrix.matrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matrix accesses',
                'unique_together': {('matrix', 'user')},
            },
        ),
    ]
