name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        python manage.py test matrix
      env:
        DJANGO_SETTINGS_MODULE: eisenhower_matrix.settings
        SECRET_KEY: 'test-key-for-ci'
        DEBUG: 'True'

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
        buildkitd-flags: --debug
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: eisenhower-matrix:latest
        outputs: type=docker,dest=/tmp/docker-image.tar
        provenance: false
        cache-from: |
          type=gha,scope=${{ github.workflow }}
        cache-to: |
          type=gha,scope=${{ github.workflow }},mode=max
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: /tmp/docker-image.tar
        retention-days: 1
        if-no-files-found: error